# Netlify ANTI-502 Config for FutPro VIP
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Variables críticas para evitar errores 502
  VITE_AUTO_CONFIRM_SIGNUP = "true"
  VITE_PRODUCTION_MODE = "true"

# === REDIRECTS OPTIMIZADOS ===
[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/oauth/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/callback*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# === HEADERS ANTI-502 OPTIMIZADOS ===
[[headers]]
  for = "/*"
  [headers.values]
    # Security básica
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    
    # CSP ANTI-502: Muy permisivo para Supabase
    Content-Security-Policy = """
      default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;
      script-src * 'unsafe-inline' 'unsafe-eval';
      style-src * 'unsafe-inline';
      img-src * data: blob:;
      font-src * data:;
      connect-src *;
      frame-src *;
      object-src 'none';
    """
    
    # Headers específicos para Supabase API
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    Access-Control-Allow-Headers = "*"
    Access-Control-Max-Age = "86400"
    
    # Headers de rendimiento
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# === EDGE FUNCTIONS (si es necesario) ===
[edge_functions]
  # Disabled para evitar interferencias con Supabase

# === FUNCTIONS CONFIG ===
[functions]
  directory = "functions"
  # Configuración de timeouts extendidos
  timeout = 30