name: FutPro CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      VITE_API_URL: https://futpro.vip/api
      NODE_ENV: production
    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v4

      - name: Instalar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Instalar dependencias (npm ci)
        run: npm ci

      - name: Lint autom치tico con ESLint
        run: npx eslint . --ext .js,.jsx

      - name: Ejecutar tests backend (ping y ranking)
        run: npx jest -c jest.backend.config.cjs --runInBand testing/ping.test.js testing/ranking-new.test.js

      - name: Ejecutar tests frontend (incluye integraci칩n)
        run: npx jest -c jest.frontend.config.cjs --runInBand

      - name: Generar reporte de cobertura
        run: |
          npx jest -c jest.backend.config.cjs --coverage --runInBand testing/ping.test.js testing/ranking-new.test.js
          npx jest -c jest.frontend.config.cjs --coverage --runInBand
        continue-on-error: true

      - name: Subir cobertura a GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Build de producci칩n (React/Vite)
        run: npm run build

      # Nota: El deploy se realiza con Netlify conectado al repo (recomendado).
      # Si deseas deploy desde Actions, agrega un job que use Netlify CLI con NETLIFY_AUTH_TOKEN y NETLIFY_SITE_ID.
