name: Deploy to Netlify (futpro.vip)

on:
  push:
    branches: [ "master" ]

concurrency:
  group: netlify-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build
        env:
          # Variables mínimas para que el registro funcione en el build
          VITE_SUPABASE_URL: https://qqrxetxcglwrejtblwut.supabase.co
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify (prod)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --prod --dir=dist --site=${{ secrets.NETLIFY_SITE_ID }}
